------------------------------------------------------------------------------------------------------------------------

[2018-02-20 12:07:51 #1 explorer] 
[ObjectDB 2.7.4_02] javax.persistence.PersistenceException
Attempt to open a database file 'C:\Users\Issur\Downloads\EclipsePortable\Data\workspace\Marron2_2018\flights.odb' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'C:\Users\Issur\Downloads\EclipsePortable\Data\workspace\Marron2_2018\flights.odb' that is currently in use by another process
	at com.objectdb.o.MSG.a(MSG.java:64)
	at com.objectdb.o.LFL.J(LFL.java:930)
	at com.objectdb.o.LFL.x(LFL.java:887)
	at com.objectdb.o.LFL.x(LFL.java:797)
	at com.objectdb.o.DFL.<init>(DFL.java:241)
	at com.objectdb.o.DMG.<init>(DMG.java:27)
	at com.objectdb.o.MST.<init>(MST.java:127)
	at com.objectdb.o.MST.ao(MST.java:109)
	at com.objectdb.o.MSF.YA(MSF.java:190)
	at com.objectdb.o.OMF.r(OMF.java:783)
	at com.objectdb.jpa.EMF.r(EMF.java:130)
	at com.objectdb.o.OMF.w(OMF.java:694)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:149)
	... 17 more

------------------------------------------------------------------------------------------------------------------------

[2018-02-20 12:08:01 #1 explorer] 
[ObjectDB 2.7.4_02] javax.persistence.PersistenceException
Attempt to open a database file 'C:\Users\Issur\Downloads\EclipsePortable\Data\workspace\Marron2_2018\flights.odb' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'C:\Users\Issur\Downloads\EclipsePortable\Data\workspace\Marron2_2018\flights.odb' that is currently in use by another process
	at com.objectdb.o.MSG.a(MSG.java:64)
	at com.objectdb.o.LFL.J(LFL.java:930)
	at com.objectdb.o.LFL.x(LFL.java:887)
	at com.objectdb.o.LFL.x(LFL.java:797)
	at com.objectdb.o.DFL.<init>(DFL.java:241)
	at com.objectdb.o.DMG.<init>(DMG.java:27)
	at com.objectdb.o.MST.<init>(MST.java:127)
	at com.objectdb.o.MST.ao(MST.java:109)
	at com.objectdb.o.MSF.YA(MSF.java:190)
	at com.objectdb.o.OMF.r(OMF.java:783)
	at com.objectdb.jpa.EMF.r(EMF.java:130)
	at com.objectdb.o.OMF.w(OMF.java:694)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:149)
	... 17 more

------------------------------------------------------------------------------------------------------------------------

[2018-02-20 12:08:41 #1 store] 
Database 'C:\Users\Issur\Downloads\EclipsePortable\Data\workspace\Marron2_2018\flights.odb' has been recovered (tr. 1-7)

[2018-02-20 12:08:41 #2 store] 
Database 'C:\Users\Issur\Downloads\EclipsePortable\Data\workspace\Marron2_2018\flights.odb' is opened by 3904@Lenovo-PC

[2018-02-20 12:08:41 #3 store] 
Configuration path: C:\Users\Issur\Desktop\LabPilotsLogin\objectdb-2.7.4_02\objectdb.conf

[2018-02-20 12:09:20 #4 store] 
Database 'C:\Users\Issur\Downloads\EclipsePortable\Data\workspace\Marron2_2018\flights.odb' is closed by 3904@Lenovo-PC

------------------------------------------------------------------------------------------------------------------------

[2018-02-20 16:13:06 #1 store] 
Database 'C:\Users\Issur\Downloads\EclipsePortable\Data\workspace\Marron2_2018\flights.odb' is opened by 11880@Lenovo-PC

[2018-02-20 16:13:06 #2 store] 
Configuration path: C:\Users\Issur\Desktop\LabPilotsLogin\objectdb-2.7.4_02\objectdb.conf

[2018-02-20 16:13:33 #3 store] 
Database 'C:\Users\Issur\Downloads\EclipsePortable\Data\workspace\Marron2_2018\flights.odb' is closed by 11880@Lenovo-PC

